name: Build-aws
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build and Publish projekt
        run: |
          dotnet restore 
          dotnet publish -c Release -o ./publish

      - name: Create zip package
        run: |
          cd ./publish
          zip -r ../ApiProjekt.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Api-projekt
          environment_name: Api-projekt-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: ApiProjekt.zip
