name: Build and push to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

- name: Build projekt 
  run:
  dornet restore ApiProjekt/ApiProjekt.csporj
  dotnet publish ApiProjekt/Apiprojekt.csporj

      - name: Create zip package
        run: 
         cd ApiProjekt; zip ../ApiProjekt.zip *;

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ }}
