name: Build and push to AWS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: 
          dotnet restore 
          dotnet publish 
        
      - name: Create zip package
        run: 
         cd site; zip ../site.zip *;

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ }}
          application_name: Api projekt
          environment_name: Api-projekt-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: site.zip
